[profile.default]
# The source directory
src = 'contracts'
# The artifact directory
out = 'out'
# A list of paths to look for libraries in
libs = ['node_modules', 'lib']
# The test directory
test = 'test/foundry'
# Whether to cache builds or not
cache = true
# The cache directory if enabled
cache_path  = 'forge-cache'
# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 7500
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = true
remappings = ['forge-std=lib/forge-std/src', '@openzeppelin/=lib/openzeppelin-contracts', '@compoundV3/=lib/comet', 'test/=test/foundry']

gas_limit = "18446744073709551615"
# For more config options see: https://book.getfoundry.sh/reference/config.html
