/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITerm, ITermInterface } from "../ITerm";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "internalAmount",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "internalAssets",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "underlyingAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "ytDestination",
        type: "address",
      },
      {
        internalType: "address",
        name: "ptDestination",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "ytBeginDate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiration",
        type: "uint256",
      },
    ],
    name: "lock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "destination",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "tokenIDs",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amount",
        type: "uint256[]",
      },
    ],
    name: "unlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITerm__factory {
  static readonly abi = _abi;
  static createInterface(): ITermInterface {
    return new utils.Interface(_abi) as ITermInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ITerm {
    return new Contract(address, _abi, signerOrProvider) as ITerm;
  }
}
