/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MockYieldAdapterInterface extends utils.Interface {
  functions: {
    "UNLOCKED_PT_ID()": FunctionFragment;
    "UNLOCKED_YT_ID()": FunctionFragment;
    "balanceOf(uint256,address)": FunctionFragment;
    "batchTransferFrom(address,address,uint256[],uint256[])": FunctionFragment;
    "decimals()": FunctionFragment;
    "factory()": FunctionFragment;
    "finalizedTerms(uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "linkerCodeHash()": FunctionFragment;
    "lock(uint256[],uint256[],uint256,address,address,uint256,uint256)": FunctionFragment;
    "name(uint256)": FunctionFragment;
    "one()": FunctionFragment;
    "perTokenApprovals(uint256,address,address)": FunctionFragment;
    "setApproval(uint256,address,uint256)": FunctionFragment;
    "setApprovalBridge(uint256,address,uint256,address)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "sharesPerExpiry(uint256)": FunctionFragment;
    "symbol(uint256)": FunctionFragment;
    "token()": FunctionFragment;
    "totalSupply(uint256)": FunctionFragment;
    "transferFrom(uint256,address,address,uint256)": FunctionFragment;
    "transferFromBridge(uint256,address,address,uint256,address)": FunctionFragment;
    "unlock(address,uint256[],uint256[])": FunctionFragment;
    "vault()": FunctionFragment;
    "yieldTerms(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "UNLOCKED_PT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNLOCKED_YT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferFrom",
    values: [string, string, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizedTerms",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "linkerCodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lock",
    values: [
      BigNumberish[],
      BigNumberish[],
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "one", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "perTokenApprovals",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setApproval",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalBridge",
    values: [BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesPerExpiry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "symbol",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFromBridge",
    values: [BigNumberish, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unlock",
    values: [string, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "yieldTerms",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UNLOCKED_PT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNLOCKED_YT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizedTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkerCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "one", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "perTokenApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesPerExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFromBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yieldTerms", data: BytesLike): Result;

  events: {};
}

export interface MockYieldAdapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockYieldAdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    UNLOCKED_PT_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    "UNLOCKED_PT_ID()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    UNLOCKED_YT_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    "UNLOCKED_YT_ID()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "balanceOf(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    batchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "batchTransferFrom(address,address,uint256[],uint256[])"(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    "decimals()"(overrides?: CallOverrides): Promise<[number]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    finalizedTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { pricePerShare: BigNumber; interest: BigNumber }
    >;

    "finalizedTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { pricePerShare: BigNumber; interest: BigNumber }
    >;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isApprovedForAll(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    linkerCodeHash(overrides?: CallOverrides): Promise<[string]>;

    "linkerCodeHash()"(overrides?: CallOverrides): Promise<[string]>;

    lock(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "lock(uint256[],uint256[],uint256,address,address,uint256,uint256)"(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "name(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    one(overrides?: CallOverrides): Promise<[BigNumber]>;

    "one()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    perTokenApprovals(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "perTokenApprovals(uint256,address,address)"(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setApproval(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setApproval(uint256,address,uint256)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovalBridge(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setApprovalBridge(uint256,address,uint256,address)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setApprovalForAll(address,bool)"(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sharesPerExpiry(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sharesPerExpiry(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    symbol(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "symbol(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    "token()"(overrides?: CallOverrides): Promise<[string]>;

    totalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "totalSupply(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferFrom(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferFrom(uint256,address,address,uint256)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFromBridge(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferFromBridge(uint256,address,address,uint256,address)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlock(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "unlock(address,uint256[],uint256[])"(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vault(overrides?: CallOverrides): Promise<[string]>;

    "vault()"(overrides?: CallOverrides): Promise<[string]>;

    yieldTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { shares: BigNumber; pt: BigNumber }>;

    "yieldTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { shares: BigNumber; pt: BigNumber }>;
  };

  UNLOCKED_PT_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "UNLOCKED_PT_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  UNLOCKED_YT_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "UNLOCKED_YT_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "balanceOf(uint256,address)"(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  batchTransferFrom(
    from: string,
    to: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "batchTransferFrom(address,address,uint256[],uint256[])"(
    from: string,
    to: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  finalizedTerms(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { pricePerShare: BigNumber; interest: BigNumber }
  >;

  "finalizedTerms(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { pricePerShare: BigNumber; interest: BigNumber }
  >;

  isApprovedForAll(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isApprovedForAll(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  linkerCodeHash(overrides?: CallOverrides): Promise<string>;

  "linkerCodeHash()"(overrides?: CallOverrides): Promise<string>;

  lock(
    assetIds: BigNumberish[],
    assetAmounts: BigNumberish[],
    underlyingAmount: BigNumberish,
    ytDestination: string,
    ptDestination: string,
    ytBeginDate: BigNumberish,
    expiration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "lock(uint256[],uint256[],uint256,address,address,uint256,uint256)"(
    assetIds: BigNumberish[],
    assetAmounts: BigNumberish[],
    underlyingAmount: BigNumberish,
    ytDestination: string,
    ptDestination: string,
    ytBeginDate: BigNumberish,
    expiration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "name(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  one(overrides?: CallOverrides): Promise<BigNumber>;

  "one()"(overrides?: CallOverrides): Promise<BigNumber>;

  perTokenApprovals(
    arg0: BigNumberish,
    arg1: string,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "perTokenApprovals(uint256,address,address)"(
    arg0: BigNumberish,
    arg1: string,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setApproval(
    tokenID: BigNumberish,
    operator: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setApproval(uint256,address,uint256)"(
    tokenID: BigNumberish,
    operator: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovalBridge(
    tokenID: BigNumberish,
    operator: string,
    amount: BigNumberish,
    caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setApprovalBridge(uint256,address,uint256,address)"(
    tokenID: BigNumberish,
    operator: string,
    amount: BigNumberish,
    caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    _operator: string,
    _approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setApprovalForAll(address,bool)"(
    _operator: string,
    _approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sharesPerExpiry(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sharesPerExpiry(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  symbol(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "symbol(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  token(overrides?: CallOverrides): Promise<string>;

  "token()"(overrides?: CallOverrides): Promise<string>;

  totalSupply(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "totalSupply(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferFrom(
    tokenID: BigNumberish,
    source: string,
    destination: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferFrom(uint256,address,address,uint256)"(
    tokenID: BigNumberish,
    source: string,
    destination: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFromBridge(
    tokenID: BigNumberish,
    source: string,
    destination: string,
    amount: BigNumberish,
    caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferFromBridge(uint256,address,address,uint256,address)"(
    tokenID: BigNumberish,
    source: string,
    destination: string,
    amount: BigNumberish,
    caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlock(
    destination: string,
    tokenIds: BigNumberish[],
    amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "unlock(address,uint256[],uint256[])"(
    destination: string,
    tokenIds: BigNumberish[],
    amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vault(overrides?: CallOverrides): Promise<string>;

  "vault()"(overrides?: CallOverrides): Promise<string>;

  yieldTerms(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { shares: BigNumber; pt: BigNumber }>;

  "yieldTerms(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { shares: BigNumber; pt: BigNumber }>;

  callStatic: {
    UNLOCKED_PT_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "UNLOCKED_PT_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    UNLOCKED_YT_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "UNLOCKED_YT_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOf(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchTransferFrom(address,address,uint256[],uint256[])"(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    finalizedTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { pricePerShare: BigNumber; interest: BigNumber }
    >;

    "finalizedTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { pricePerShare: BigNumber; interest: BigNumber }
    >;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isApprovedForAll(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    linkerCodeHash(overrides?: CallOverrides): Promise<string>;

    "linkerCodeHash()"(overrides?: CallOverrides): Promise<string>;

    lock(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "lock(uint256[],uint256[],uint256,address,address,uint256,uint256)"(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    name(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "name(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    one(overrides?: CallOverrides): Promise<BigNumber>;

    "one()"(overrides?: CallOverrides): Promise<BigNumber>;

    perTokenApprovals(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "perTokenApprovals(uint256,address,address)"(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setApproval(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setApproval(uint256,address,uint256)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalBridge(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setApprovalBridge(uint256,address,uint256,address)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setApprovalForAll(address,bool)"(
      _operator: string,
      _approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    sharesPerExpiry(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sharesPerExpiry(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "symbol(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    token(overrides?: CallOverrides): Promise<string>;

    "token()"(overrides?: CallOverrides): Promise<string>;

    totalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "totalSupply(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferFrom(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferFrom(uint256,address,address,uint256)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferFromBridge(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferFromBridge(uint256,address,address,uint256,address)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unlock(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "unlock(address,uint256[],uint256[])"(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<string>;

    "vault()"(overrides?: CallOverrides): Promise<string>;

    yieldTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { shares: BigNumber; pt: BigNumber }>;

    "yieldTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { shares: BigNumber; pt: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    UNLOCKED_PT_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "UNLOCKED_PT_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    UNLOCKED_YT_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "UNLOCKED_YT_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOf(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "batchTransferFrom(address,address,uint256[],uint256[])"(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    finalizedTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "finalizedTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isApprovedForAll(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    linkerCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    "linkerCodeHash()"(overrides?: CallOverrides): Promise<BigNumber>;

    lock(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "lock(uint256[],uint256[],uint256,address,address,uint256,uint256)"(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "name(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    one(overrides?: CallOverrides): Promise<BigNumber>;

    "one()"(overrides?: CallOverrides): Promise<BigNumber>;

    perTokenApprovals(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "perTokenApprovals(uint256,address,address)"(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setApproval(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setApproval(uint256,address,uint256)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovalBridge(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setApprovalBridge(uint256,address,uint256,address)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setApprovalForAll(address,bool)"(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sharesPerExpiry(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sharesPerExpiry(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "symbol(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    "token()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "totalSupply(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferFrom(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferFrom(uint256,address,address,uint256)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFromBridge(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferFromBridge(uint256,address,address,uint256,address)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlock(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "unlock(address,uint256[],uint256[])"(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;

    "vault()"(overrides?: CallOverrides): Promise<BigNumber>;

    yieldTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "yieldTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    UNLOCKED_PT_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "UNLOCKED_PT_ID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UNLOCKED_YT_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "UNLOCKED_YT_ID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "batchTransferFrom(address,address,uint256[],uint256[])"(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finalizedTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "finalizedTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isApprovedForAll(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    linkerCodeHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "linkerCodeHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lock(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "lock(uint256[],uint256[],uint256,address,address,uint256,uint256)"(
      assetIds: BigNumberish[],
      assetAmounts: BigNumberish[],
      underlyingAmount: BigNumberish,
      ytDestination: string,
      ptDestination: string,
      ytBeginDate: BigNumberish,
      expiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "name(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    one(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "one()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    perTokenApprovals(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "perTokenApprovals(uint256,address,address)"(
      arg0: BigNumberish,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setApproval(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setApproval(uint256,address,uint256)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalBridge(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setApprovalBridge(uint256,address,uint256,address)"(
      tokenID: BigNumberish,
      operator: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setApprovalForAll(address,bool)"(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sharesPerExpiry(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sharesPerExpiry(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "symbol(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "token()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "totalSupply(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferFrom(uint256,address,address,uint256)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFromBridge(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferFromBridge(uint256,address,address,uint256,address)"(
      tokenID: BigNumberish,
      source: string,
      destination: string,
      amount: BigNumberish,
      caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlock(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "unlock(address,uint256[],uint256[])"(
      destination: string,
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "vault()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yieldTerms(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "yieldTerms(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
