name: Lint

on:
  push:
    branches:
    - main
  pull_request:

jobs:

    lint:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: init
        run: npm ci

      - name: Style Check
        run: npm run style-check

      - name: Solhint
        run: npm run solhint

      - name: Spell Check
        run: npm run spell-check
