name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check:
    name: CheckPRCurrent
    runs-on: ubuntu-latest
    steps:
      - name: Handle pull request
        if: github.event_name != 'push'
        uses: Automattic/action-pr-is-up-to-date@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          tags: latest

      - name: Handle tag push
        if: github.event_name == 'push'
        uses: Automattic/action-pr-is-up-to-date@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          tag: latest
    unit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
            node-version: 14
        - name: Install dependencies
          run: npm ci 
        - name: compile
          run: npx hardhat compile
        - name: test
          run: npm run test
    sim:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
            node-version: 14
        - name: Install dependencies
          run: npm ci
        - name: simulation
          run:
            npm run sim
    foundry:
      name: foundry/unit
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
          with:
            version: nightly
        - name: Run tests
          run: forge test -vvv
    typecheck:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
            node-version: 14
        - name: Install dependencies
          run: npm ci 
        - name: compile
          run: npx hardhat compile
        - name: typecheck
          run: npm run typecheck
